name: CI

on:
  push:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      # Set up Rust
      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.0

      # Test
      - name: Test
        run: cargo test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.0

      - name: Format
        run: cargo fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust and Cargo
        uses: moonrepo/setup-rust@v1.2.0

      - name: Lint
        run: cargo clippy -- --deny warnings

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
